### ISSUE TITLE
Ability to configure roles for `gcloud_iam` provider

### ISSUE THREAD

**Issue by bsushmith** [odpf/guardian#184] opened 2022-06-21 16:13 UTC
**Summary**
At the moment, for every provider one can configure a set of roles with permission sets. It enables one to control the access roles to which a user can raise appeals for.

Bigquery example - https://odpf.github.io/guardian/docs/providers/bigquery#yaml-representation which has roles and permission set for each resource type.

This is not true for `gcloud_iam` provider. Only this provider does not have a way to take in the configured roles/permissions from the provider config file. Due to which if the `gcloud_iam` is exposed as a provider to users, the [GetRoles](https://github.com/odpf/guardian/blob/main/plugins/providers/gcloudiam/provider.go#L114) method will fetch **every** iam role  available in GCP. If one wants to restrict users to only a certain roles through guardian like other providers, they cannot currently., and the user would be able to raise an appeal for any **role** in gcp.

**Proposed solution**
Modify the gcp provider to 
* get roles from the provider config if roles are provided, and use them as the only roles available for appeals.
* continue as it is in the current form if the roles are not provided in the provider config.

**Comment by ravisuhag** [comment] 2022-08-02 00:42
@bsushmith @rahmatrhd is this duplicate of #218?

**Comment by rahmatrhd** [comment] 2022-08-02 06:07
@ravisuhag not initially, but now the discussion for this also happens in #218

**Comment by ravisuhag** [comment] 2022-08-15 11:05
Covered in #218

**Closed by ravisuhag** 2022-08-15 11:05 UTC
Labels: enhancement, provider, gcloud_iam
